### ISSUE TITLE
添加集群,连接成功后报错create common user failed: strconv.Atoi: parsing "13+": invalid syntax[Bug]

### ISSUE THREAD

**Issue by spiritman1990** [KubeOperator/KubePi#10]
**KubePi 版本**
kubeoperator/kubepi-server:latest 镜像

**Kubernetes 版本**
v1.13.10-r1-CCE2.0.28.B001 |  

**Bug 描述**
添加完集群后，对集群进行授权，报错： 
create common user failed: strconv.Atoi: parsing "13+": invalid syntax

**Bug 重现步骤(有截图更好)**
1. ![image](https://user-images.githubusercontent.com/14070910/135215592-e66199e5-1d9a-487a-8497-809723a6f382.png)

**Comment by wanghe-fit2cloud** [comment]
你好，KubePi 目前已适配的 Kubernetes 版本有：v1.16 ~ v1.20。
你的问题我们也已收到，会在近期版本中适配

**Comment by spiritman1990** [comment]
> 你好，KubePi 目前已适配的 Kubernetes 版本有：v1.16 ~ v1.20。 你的问题我们也已收到，会在近期版本中适配

好的，希望尽快给适配一下，生产的还是1.13
