### ISSUE TITLE
[Bug] #1、k8s 概览 页面 ***

### ISSUE THREAD

**Issue by alivv** [KubeOperator/KubePi#100]
**KubePi 版本**
v1.5.3

**Kubernetes 版本**
v1.18.8

**Bug 描述**
集群CPU,内存使用率统计
没集群nodes的list,get权限时有如下提示"未能检测到metric server服务,点击安装或重置"(没权限点击安装会报错)
应该做判断, 没nodes权限时直接屏蔽, 有权限且没检测到metric时提示安装

**Bug 重现步骤(有截图更好)**
1、新建用户, 使用Common User角色, k8s集群添加用户并只配置"命名空间角色"的权限, 不添加"集群角色"
2、新用户登录并打开k8s集群, 就会没集群nodes的list,get权限, CPU,内存使用率统计的地方报错

**Comment by ssongliu** [comment]
新版本 1.6.0 已解决该问题，感谢反馈！
