### ISSUE TITLE
[Bug] #2、自定义命名空间角色,没“详情”字段 **

### ISSUE THREAD

**Issue by alivv** [KubeOperator/KubePi#101]
**KubePi 版本**
v1.5.3

**Kubernetes 版本**
v1.18.8

**Bug 描述**

2.1 集群详情,角色,命名空间，创建, 没“详情”(创建集群角色有"详情")
单独编辑role添加metadata.annotations.description后, 但使用kubepi编辑后丢失description

2.2 角色.存活时间,取值role的metadata.annotations.created-at值, 使用yml自定义的role没created-at值而存活时间一直空着, 应该可以直接取值metadata.creationTimestamp
(延伸: 存活时间,可以使用"创建时间"替代;  k8s集群列表的"存活时间"应该使用"添加时间"替代,或直接去掉,集群的"存活时间"存在歧义)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。

**Comment by ssongliu** [comment]
新版本 1.6.0 已优化该部分显示，感谢反馈！
