### ISSUE TITLE
[Feature] #3、ingress显示 **

### ISSUE THREAD

**Issue by alivv** [KubeOperator/KubePi#102]
**请描述您的需求或者改进建议.**

ingress页面"目标"栏目显示全部"域名--->svc:prot"有点乱,建议默认最多显示10个,添加”更多“按钮
(有些项目微服务后端接口地址很多，几百个)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。

**Comment by ssongliu** [comment]
新版本 1.6.0 已优化该部分显示，感谢反馈！
