### ISSUE TITLE
[Feature]  #4、Pods列表 ****

### ISSUE THREAD

**Issue by alivv** [KubeOperator/KubePi#103]
**请描述您的需求或者改进建议.**

pod列表, 增加故障pod醒目标识
top Pod 增加排序restart
pod详情里可以增加pod内存, cpu使用率趋势图,需要配合prometheus,可以像Lens支持自定义prometheus地址

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。

**Comment by ssongliu** [comment]
新版本 1.6.0 已对 pod 列表及top pod 显示进行了优化，pod 详情增加趋势图近期不会考虑，感谢反馈！
