### ISSUE TITLE
[Bug] #6、configmap权限 ***

### ISSUE THREAD

**Issue by alivv** [KubeOperator/KubePi#105]
**KubePi 版本**
v1.5.3

**Kubernetes 版本**
v1.18.8

**Bug 描述**

新建命名空间权限, 自定义configmap写权限
API *
资源 [ "configmaps" ]
动作 *
动作为*时可以打开configmaps编辑页面, 
给予其它所有权限都无效会弹回"概览"页面
(所有权限："list", "get", "watch", "update", "patch", "create", "deletecollection", "delete" )

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。

**Comment by ssongliu** [comment]
新版本 1.6.0 已解决该问题，感谢反馈！
