### ISSUE TITLE
[Bug] #7、权限混乱,多次安装kubepi特例 **

### ISSUE THREAD

**Issue by alivv** [KubeOperator/KubePi#106]
**KubePi 版本**
v1.5.3

**Kubernetes 版本**
v1.18.8

**Bug 描述**

删除kubepi后再次部署kubepi并创建相同用户, 遗留上次部署配置的权限RoleBinding造成权限混乱
最后查得是遗留上次部署配置的权限RoleBinding, 手动删除解决
(帮助文档里可添加相关提示, 若彻底删除kubepi需先删除k8s用户授权和自定义权限)

**Bug 重现步骤(有截图更好)**
1、k8s部署kubepi,添加k8s集群和创建dev用户,给予dev用户部分namespace权限, 测试完成后删除kubepi并手动删除kubepi.db文件
2、重新部署kubepi, 添加相同的k8s集群test和用户dev, 并添加dev用户权限, 在并未添加名称为test1(上次部署添加过)的namespace权限情况下, 下拉框有test1选项, 选择后会报错
3、重新添加test1的namespace权限后再次删除, 还是无法去除去除下拉框”test1“选项

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。

**Comment by ssongliu** [comment]
新版本 1.6.0 已解决该问题，感谢反馈！
