### ISSUE TITLE
[Bug] #8、安全 *****

### ISSUE THREAD

**Issue by alivv** [KubeOperator/KubePi#107]
**KubePi 版本**
v1.5.3

**Kubernetes 版本**
v1.18.8

**Bug 描述**

1、打开容器日志和进入容器终端页面, 主动退出用户登录, 容器日志和终端页面并未退继续可用
(容器日志和终端页面,在退出账户和长时间不操作时应断开连接, 能针对不同集群自定义时间更好)；

2、登录超时和缓存, 笔记本电脑盒盖几小时后, 不需要重新登录kubepi即可继续使用
(默认超时时间多久, 能否自定义)

3、容器日志和终端页面, 打开数量是否有限制;
打开几十个容器日志页面后,若忘记关闭页面, 会不会一直刷新日志造成k8s apiserver崩溃

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。

**Comment by ssongliu** [comment]
新版本 1.6.0 已对该问题进行如下优化：
1. 系统支持自定义过期时间（配置文件中），无操作时默认 1 天自动退出登陆，退出系统将使终端、日志不可用；
2. 终端及日志设置为 5 分钟内无操作自动断开；
