### ISSUE TITLE
[Bug] 应用市场点击应用详情，切换版本过慢

### ISSUE THREAD

**Issue by yuntianfeijing** [KubeOperator/KubePi#109]
**KubePi 版本**
所有版本

**Kubernetes 版本**
不限定

**Bug 描述**
应用市场点击应用详情，切换版本过慢

**Bug 重现步骤(有截图更好)**
1. 应用市场添加charts仓库 	https://charts.bitnami.com/bitnami
2. 应用中点击任意应用 此过程超级慢 	
涉及接口：
/kubepi/api/v1/charts/{cluster}/{name}?repo={repo}
此接口每次都会重新缓存 charts.txt   及 index.yaml 到相应  ~/.cache/helm/repository 目录，且命名规则貌似hash，每次调用，该目录下就会多俩文件，且不会被使用

 ~/.cache/helm/repository 下的repository 缓存信息应该被命名为
 {repo}-charts.txt  {repo}-index.yaml 且能够被search缓存命中

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。
后续版本会针对上述问题做出优化。

**Comment by yuntianfeijing** [comment]
![c8fba2bd3c8b4224f282ddb48c498d6](https://user-images.githubusercontent.com/42763234/180952285-d1d1358f-252e-4421-890e-50f6f8a8edac.jpg)

**Comment by zhengkunwang223** [comment]
> ![c8fba2bd3c8b4224f282ddb48c498d6](https://user-images.githubusercontent.com/42763234/180952285-d1d1358f-252e-4421-890e-50f6f8a8edac.jpg)

不好意思,没有复现这个问题,我们的.cache目录下面会根据集群名称生成文件夹,缓存文件名称没有hash处理,也是根据仓库名称来生成的

例如:
~/.cache/helm/{clustername}/repository/{reponame}-charts.txt
~/.cache/helm/{clustername}/repository/{reponame}-index.yaml

**Comment by wanghe-fit2cloud** [comment]
最新版本 v1.6.1 已尝试优化。

**Comment by yuntianfeijing** [comment]
> > ![c8fba2bd3c8b4224f282ddb48c498d6](https://user-images.githubusercontent.com/42763234/180952285-d1d1358f-252e-4421-890e-50f6f8a8edac.jpg)
> 
> 不好意思,没有复现这个问题,我们的.cache目录下面会根据集群名称生成文件夹,缓存文件名称没有hash处理,也是根据仓库名称来生成的
> 
> 例如: ~/.cache/helm/{clustername}/repository/{reponame}-charts.txt ~/.cache/helm/{clustername}/repository/{reponame}-index.yaml

![image](https://user-images.githubusercontent.com/42763234/182554213-01013095-5adf-4013-a72b-d04b2afbe7c9.png)
并不是~/.cache/helm/{clustername}/repository/目录，是~/.cache/helm/repository/ 目录

**Comment by yuntianfeijing** [comment]
> 最新版本 v1.6.1 已尝试优化。

经测试 v1.6.1 并未解决
