### ISSUE TITLE
关于KubePi添加docker私服时自动为docker和containerd配置http协议访问配置的建议

### ISSUE THREAD

**Issue by yangandiris** [KubeOperator/KubePi#110]
一般我们添加的docker私服都是走的http协议，在拉取镜像时默认都是走的https协议，需要对docker和containerd进行配置才能走http协议，但是一般集群环境下服务器数量非常多，一个个配置起来非常头疼，建议在KubePi添加docker私服时自动给docker或containerd加上配置，望采纳！

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。
我们会在后续版本中考虑上述需求。
