### ISSUE TITLE
[Bug]使用文件浏览器下载文件，会存在超时无法下载问题

### ISSUE THREAD

**Issue by chenxin2001** [KubeOperator/KubePi#111]
**KubePi 版本**
v1.6.1

**Kubernetes 版本**
1.22

**Bug 描述**
使用文件浏览器下载某些个别文件，会存在超时无法下载问题。页面返回nginx timeout错误。

**Bug 重现步骤(有截图更好)**
1.进入kubepi的某个集群中，选择“工作负载-Pods”，点击更多按钮选择“文件浏览器”；
2.选择个别日志文件，点击下载，提示nginx timeout，无法下载；
3.个别文件（11m左右）存在这个问题，其他文件日志（大于11m的文件）也能正常下载；
4.返回该问题文件的上层目录，点击下载整个目录。目录文件可正常下载，但是解压提示文件损坏。
![image](https://user-images.githubusercontent.com/34565342/182792486-a993f803-5cf7-44ea-8d12-c04a3d43a9e7.jpeg)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。
