### ISSUE TITLE
应用市场

### ISSUE THREAD

**Issue by yuntianfeijing** [KubeOperator/KubePi#112]
> ![c8fba2bd3c8b4224f282ddb48c498d6](https://user-images.githubusercontent.com/42763234/180952285-d1d1358f-252e-4421-890e-50f6f8a8edac.jpg)

不好意思,没有复现这个问题,我们的.cache目录下面会根据集群名称生成文件夹,缓存文件名称没有hash处理,也是根据仓库名称来生成的

例如:
~/.cache/helm/{clustername}/repository/{reponame}-charts.txt
~/.cache/helm/{clustername}/repository/{reponame}-index.yaml

_Originally posted by @zhengkunwang223 in https://github.com/KubeOperator/KubePi/issues/109#issuecomment-1197726637_

**Comment by yuntianfeijing** [comment]
是 ~/.cache/helm/repository  目录，而不是带{clustername} 的目录

**Comment by yuntianfeijing** [comment]
![image](https://user-images.githubusercontent.com/42763234/182795613-319a29e3-a343-4937-8a7b-64cd403eb6e1.png)
建议如此修改

**Comment by wanghe-fit2cloud** [comment]
Get.

**Comment by yuntianfeijing** [comment]
原因参考：
https://github.com/helm/helm/blob/main/pkg/repo/chartrepo.go#L233-L247
在client设置 RepoURL时，会重新获取charts.txt及 index.yaml，且命名时随机base64命名的

**Comment by zhengkunwang223** [comment]
> 原因参考： https://github.com/helm/helm/blob/v3.9.2/pkg/action/install.go#L718 https://github.com/helm/helm/blob/v3.9.2/pkg/repo/chartrepo.go#L233-L247 在client设置 RepoURL时，会重新获取charts.txt及 index.yaml，且依随机[]byte 并base64命名文件前缀

您好 注释掉 client.RepoURL = re.URL 这行会导致获取不到hem chart 包
