### ISSUE TITLE
[Bug] LoadBalancer Service 不显示 ExternalIP

### ISSUE THREAD

**Issue by zyxlinux** [KubeOperator/KubePi#113]
**KubePi 版本**
1.6.1

**Kubernetes 版本**
1.23.6

**Bug 描述**
通过openelb给ingress nginx分配 LoadBalancer  IP后 ExternalIP不显示 IP  kubectl get servcie可以显示 ExternalIP

**Bug 重现步骤(有截图更好)**
1.  K8S集群部署OPENELB
2. 给ingress 添加openelb注解
![image](https://user-images.githubusercontent.com/20107520/183817092-d52790e1-049a-43d8-ba18-27fc3748c78f.png)

**Comment by zyxlinux** [comment]
![image](https://user-images.githubusercontent.com/20107520/183817172-9f7e423c-da9e-481e-9e06-6841872db1b0.png)

**Comment by wanghe-fit2cloud** [comment]
Get.

**Comment by wanghe-fit2cloud** [comment]
最新版本已修复。
