### ISSUE TITLE
[Bug]在线体验集群异常

### ISSUE THREAD

**Issue by uninstall-h** [KubeOperator/KubePi#117]
**Bug 描述**
在线体验中的集群异常了

**Bug 重现步骤(有截图更好)**

![demo](https://user-images.githubusercontent.com/23739868/187643816-17e30716-3359-4348-99e8-897b7c8cc3e1.png)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。

**Comment by wanghe-fit2cloud** [comment]
已修复。
