### ISSUE TITLE
[Bug]不授予pods/exec权限，点击”终端”依然可以进入pod操作

### ISSUE THREAD

**Issue by chenyongzhi001** [KubeOperator/KubePi#123]
**KubePi 版本**
1.0

**Kubernetes 版本**
v1.20.2

**Bug 描述**
集群列表-授权-角色-命名空间-不授予pods/exec权限，点击”终端”依然可以进入pod操作

**Bug 重现步骤(有截图更好)**
1.
![dca57ff39de29e9863c7d42dca9f6b9](https://user-images.githubusercontent.com/35951080/197482229-634fae68-feee-4675-abcf-69fe88c69f36.png)

2.
![a8485b3cb81f3d9317507da12e30a0d](https://user-images.githubusercontent.com/35951080/197482756-d4958756-de82-4ad9-9385-977d2f9965a2.jpg)

3.
![image](https://user-images.githubusercontent.com/35951080/197483091-db75977d-58fc-4f8c-9db6-032c19d053a4.png)

![image](https://user-images.githubusercontent.com/35951080/197483200-0a14315f-f954-4431-9bbd-737b3ba01ce4.png)
![image](https://user-images.githubusercontent.com/35951080/197483248-ddcbdde9-2b2c-409f-999f-bb92582f3b7a.png)

**Comment by chenyongzhi001** [comment]
日志同理 不配权限  依旧可以看

**Comment by wanghe-fit2cloud** [comment]
单 Pod 单 Container，点击终端存在该问题吗？

**Comment by chenyongzhi001** [comment]
> 

一样的，包括日志也是，虽然提示API未授权，但是依旧可以看log

**Comment by wanghe-fit2cloud** [comment]
最新版本已尝试修复该问题。
