### ISSUE TITLE
[Bug]Pod 文件浏览器，有时候文件下载异常

### ISSUE THREAD

**Issue by xiatiandegaga** [KubeOperator/KubePi#125]
**KubePi 版本**
1.61

**Kubernetes 版本**

1.20.6
**Bug 描述**
pod页面-文件浏览器-下载，有时下载不了，有时下载完后解压提示压缩包损坏
目前没有成功下载过一次完整的压缩包，日志几百kb

**Bug 重现步骤(有截图更好)**
1.pod页面
2.点击文件浏览器
3.点击下载
![1666925685108](https://user-images.githubusercontent.com/47713355/198483121-bd9d5e74-a8b5-4d5a-a5a8-f8c2fbceee37.png)

**Comment by wanghe-fit2cloud** [comment]
我先在本地尝试看能不能复现吧。

**Comment by xiatiandegaga** [comment]
好的哈

**Comment by xiatiandegaga** [comment]
1.6.2版本已修复，谢谢哈。
