### ISSUE TITLE
[Question] kubepi支持多节点部署么？

### ISSUE THREAD

**Issue by hackersean** [KubeOperator/KubePi#126]
请问kubepi的数据存放是否支持数据库？
我部署在k8s上，pod挂了后配置就丢失了。看持久化配置也只是把文件放到pvc中，担心服务器挂了数据会丢。

**Comment by wanghe-fit2cloud** [comment]
持久化出来的就是数据库db文件

**Comment by hackersean** [comment]
本地的是sqlite么？似乎使用sqlite无法读取。
不知可以对接MySQL之类的数据库么？

**Comment by wanghe-fit2cloud** [comment]
数据库: [BoltDB](https://github.com/etcd-io/bbolt)
不支持对接 MySQL.
