### ISSUE TITLE
[Bug]进入容器10分钟左右不操作会出现超时断连情况

### ISSUE THREAD

**Issue by xudeheng** [KubeOperator/KubePi#128]
**KubePi 版本**
v1.6.2，v1.6.1都有

**Kubernetes 版本**
v1.2.*

**Bug 描述**

**Bug 重现步骤(有截图更好)**
![image](https://user-images.githubusercontent.com/58208803/202615508-6b17175b-ffc6-464f-8045-2a82dc429f5f.png)

1.随便进入一个可登录的pod容器
2.等待10分钟随意输入命令
3.会出现 ******** The connection failed. Unsupported, interrupted or timed out. ********
4.其他工具同样步骤没有此情况

**Comment by wanghe-fit2cloud** [comment]
终端超时时间为 10 分钟。
