### ISSUE TITLE
[Bug]MFA认证问题

### ISSUE THREAD

**Issue by YangDevops** [KubeOperator/KubePi#129]
**KubePi 版本**
 v1.6.2

**Kubernetes 版本**

**Bug 描述**
启用MFA认证以后，第二次登录的时候还是会显示MFA的秘钥KEY

**Bug 重现步骤(有截图更好)**
1.
![image](https://user-images.githubusercontent.com/24538374/202674759-27da4b91-3846-4fab-8f7e-7a93c7f758fd.png)

2.
3.

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。我们先在本地复现一下该问题。

**Comment by xuzheng0017** [comment]
我还想在这位仁兄的基础上补充2点：
1. 这个界面填写验证码后直接回车登录会报错：认证信息已过期，请重新登录。鼠标点击登录没问题
2. 这个界面汉字提示最后一个是错别字，应该是：验证码，不是：验证吗。哈哈哈

**Comment by wanghe-fit2cloud** [comment]
Get.

**Comment by wanghe-fit2cloud** [comment]
最新版本已修复。
