### ISSUE TITLE
[Bug]终端输入长命令，显示不正常

### ISSUE THREAD

**Issue by Aaron-kk** [KubeOperator/KubePi#13]
**KubePi 版本**
v1.1.0

**Kubernetes 版本**
1.18.20

**Bug 描述**
终端命令行如果够长，光标会跳到行首覆盖输入。

**Bug 重现步骤(有截图更好)**
![image](https://user-images.githubusercontent.com/25951410/138436987-b8709b34-433d-41d8-942e-2d0c63141ece.png)

**Comment by wanghe-fit2cloud** [comment]
已解决，请使用最新版本。

**Comment by Aaron-kk** [comment]
> 已解决，请使用最新版本。

为解决啊，升级到v1.2.0还是有这个bug。

**Comment by Aaron3S** [comment]
我再重新修复一下，抱歉

**Comment by topicgit** [comment]
![image](https://user-images.githubusercontent.com/11975460/145714556-e795dae0-c1ad-4242-afc1-d0bc40a2a00b.png)

1.3.0 测试依然存在这个问题 @_@

**Comment by Aaron3S** [comment]
这个问题来自上游项目,我已经提交了issues,https://github.com/kubernetes/dashboard/issues/6623
