### ISSUE TITLE
[Question] 通过一系列的安装后，发现kubepi依然是个单点

### ISSUE THREAD

**Issue by yyeexxhhh** [KubeOperator/KubePi#130]
**请描述您的问题.**
1.该数据不支持多点部署，只能是单独，在实际生产环节中这个无法做到高可用

**Comment by wanghe-fit2cloud** [comment]
KubePi 还不不支持高可用部署。

**Comment by yyeexxhhh** [comment]
是啊，所以很遗憾，在考虑重构orm那块

**Comment by wanghe-fit2cloud** [comment]
> 是啊，所以很遗憾，你们社区有考虑过支持高可用部署吗？

后续版本吧，我们考虑支持一下该需求。
