### ISSUE TITLE
[Bug]使用 config 文件导入集群失败

### ISSUE THREAD

**Issue by Shuimo03** [KubeOperator/KubePi#133]
**KubePi 版本**
master

**Kubernetes 版本**
v1.22.1

**Bug 描述**
导入集群失败，使用config文件 
message: "Get \"https://lb.kubesphere.local:6443/api/v1/namespaces\": dial tcp: lookup lb.kubesphere.local on 192.168.52.2:53: read udp 172.17.0.2:43953->192.168.52.2:53: i/o timeout"

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by wanghe-fit2cloud** [comment]
kubepi 容器内访问 lb.kubesphere.local 超时了

**Comment by Shuimo03** [comment]
是的，看了一下是不是需要弄成公网IP？换成其他方式导入也失败了，我是在vmware Workstation Pro上创建了一个三节点集群，在master节点上使用docker运行KubePi，之后导入失败了

**Comment by wanghe-fit2cloud** [comment]
应该不需要公网 IP。
将 config 文件中 server 部分替换成 master 节点的内网 IP 应该就行。
