### ISSUE TITLE
kubepi，这里建议可以支持中文，kubeoperator导入的集群支持中文

### ISSUE THREAD

**Issue by zhangjijian5** [KubeOperator/KubePi#135]
**请描述您的需求或者改进建议.**
![image](https://user-images.githubusercontent.com/43225766/210292695-365e2192-8519-4850-b17e-58478ff7b294.png)

**Comment by wanghe-fit2cloud** [comment]
需要根据导入的集群名称在 K8s 集群中创建 RBAC 等资源，不支持中文。
