### ISSUE TITLE
[Bug] 进入集群控制台后，页面上方提示红色报错：the server could not find the requested resource

### ISSUE THREAD

**Issue by gzlisanshao** [KubeOperator/KubePi#14]
**KubePi 版本**
v1.1.0

**Kubernetes 版本**
 v1.12.3 

**Bug 描述**
进入集群控制台后，页面上方提示红色报错：the server could not find the requested resource

**Bug 重现步骤(有截图更好)**
1.
2.
3.
![image](https://user-images.githubusercontent.com/47784139/138442486-290b2295-3468-455c-9a36-a595e9a38f08.png)

**Comment by wanghe-fit2cloud** [comment]
升级到最新版本后，查看是否还存在该问题。
