### ISSUE TITLE
[Bug] 自定义yaml配置异常the server does not allow this method on the requested resource

### ISSUE THREAD

**Issue by 007idle** [KubeOperator/KubePi#145]
**KubePi 版本**
latest

**Kubernetes 版本**
v1.25.6

**Bug 描述**
1. service、deployment、configMap界面通过YAML按钮进入配置页
2. 复制自定义配置
3. 提示the server does not allow this method on the requested resource

**Bug 重现步骤(有截图更好)**
1.
![image](https://user-images.githubusercontent.com/33239887/223608753-78378613-c533-444e-b9f9-52d9cdc5ea51.png)
![image](https://user-images.githubusercontent.com/33239887/223609168-baa0506b-87f0-48c8-bb84-0c811e90821d.png)

4.
5.

**Comment by wanghe-fit2cloud** [comment]
需要在 yaml 中指定 namespace.
