### ISSUE TITLE
[Feature]Service对象资源中的“选择器”建议做成下拉框可供搜索和选择相应资源

### ISSUE THREAD

**Issue by chenxin2001** [KubeOperator/KubePi#16]
**请描述您的需求或者改进建议.**
Service对象资源中的“选择器”建议做成下拉框可供搜索和选择相应资源。
如下图所示：
![image](https://user-images.githubusercontent.com/34565342/138631437-d0f0c7c3-7205-47bc-988d-75a66948723a.png)

**Comment by wanghe-fit2cloud** [comment]
最新版本已经支持创建workload时同步创建service
