### ISSUE TITLE
[Bug] 集群首页无法使用Termimal 

### ISSUE THREAD

**Issue by yeeeee7** [KubeOperator/KubePi#173]
**KubePi 版本**
1.6.5

**Kubernetes 版本**
1.23.4

**Bug 描述**
进入集群首页无法使用Termimal （帮助旁边的按钮），报错
{
  "code": 502,
  "message": "",
  "success": false
}

**Bug 重现步骤(有截图更好)**
1.hostNetwork: true 必现
2.
3.

**Comment by yeeeee7** [comment]
@wanghe-fit2cloud

**Comment by wanghe-fit2cloud** [comment]
可以先试用官方提供的安装命令来安装 KubePi。
至于 host 模式无法使用终端的问题，我们先在本地环境复现一下。

**Comment by wzxmt** [comment]
我使用docker（Docker version 23.0.1） 或者k8s（1.24.3）部署导入1.24集群、1.18集群，Terminal也无法使用

![企业微信截图_16940977168092](https://github.com/1Panel-dev/KubePi/assets/44249535/0e163597-b421-4a25-adc9-4daa4e4f1597)
