### ISSUE TITLE
[Feature]建议添加监控功能

### ISSUE THREAD

**Issue by wgy-ts** [KubeOperator/KubePi#18]
希望能加上启用监控的开关，提供prometheus-operator一键部署的功能；如果集群已经部署了prometheus组件，直接调用。可以极大提高运维能力。

**Comment by wanghe-fit2cloud** [comment]
我们还是建议在 KubeOperator 工具栏中来开启 Prometheus，而且 KubeOperator 的监控页面我们在下一个版本中也做了很大的优化。

如果是非 KubeOperator 创建的集群，在最新版本中也支持一键导入，并能通过集群页 Dashboard 功能直接跳转到 KubePi。
