### ISSUE TITLE
[Bug] node状态显示异常

### ISSUE THREAD

**Issue by gzlisanshao** [KubeOperator/KubePi#19]
**KubePi 版本**
v1.1.1

**Kubernetes 版本**
v1.20.10

**Bug 描述**
1，命令行查看node
[root@ccsoa-master-1 ~]# kubectl get nodes
NAME             STATUS     ROLES                              AGE     VERSION
ccsoa-master-1   Ready      control-plane,etcd,master,worker   7d18h   v1.20.10
ccsoa-worker-1   Ready      worker                             7d18h   v1.20.10
ccsoa-worker-2   NotReady   worker                             7d18h   v1.20.10
ccsoa-worker-3   Ready      worker                             7d18h   v1.20.10
ccsoa-worker-4   Ready      worker                             7d18h   v1.20.10
2，界面查看正常，有一个节点是关机状态

3，集群--nodes菜单查看，应该是四个节点Ready，一个节点NotReady，这里都是Active

**Bug 重现步骤(有截图更好)**
1.命令行查看node
[root@ccsoa-master-1 ~]# kubectl get nodes
NAME             STATUS     ROLES                              AGE     VERSION
ccsoa-master-1   Ready      control-plane,etcd,master,worker   7d18h   v1.20.10
ccsoa-worker-1   Ready      worker                             7d18h   v1.20.10
ccsoa-worker-2   NotReady   worker                             7d18h   v1.20.10
ccsoa-worker-3   Ready      worker                             7d18h   v1.20.10
ccsoa-worker-4   Ready      worker                             7d18h   v1.20.10
2.界面查看正常
![image](https://user-images.githubusercontent.com/47784139/139186144-312cd9f1-7f5e-417f-be8a-9765607057cd.png)

3.集群--nodes菜单查看，应该是四个节点Ready，一个节点NotReady，这里都是Active
![image](https://user-images.githubusercontent.com/47784139/139186090-92fd5baf-1fd0-4a82-bdce-6a74a000359a.png)

**Comment by wanghe-fit2cloud** [comment]
v1.1.2 版本已修复
