### ISSUE TITLE
[Bug] webkubectl 无法使用

### ISSUE THREAD

**Issue by rushsinging** [KubeOperator/KubePi#21]
**KubePi 版本**
docker latest 应该是1.1.1

**Kubernetes 版本**
1.17.17

**Bug 描述**

webkubectl 无法使用

**Bug 重现步骤(有截图更好)**
1.  启动:  docker run --privileged -d --restart=unless-stopped -p 8081:80 kubeoperator/kubepi-server
2. 
<img width="1427" alt="图片" src="https://user-images.githubusercontent.com/1578947/139390219-aabf3e2a-1b8e-436a-b7ff-e6fbe92ebbd2.png">

3. 
<img width="612" alt="图片" src="https://user-images.githubusercontent.com/1578947/139390257-e7c8455d-7db5-4f35-b310-e1a5eb124bd7.png">

**Comment by wanghe-fit2cloud** [comment]
已解决，请使用最新版本。
