### ISSUE TITLE
[Bug]二进制启动kubepi-server时，flag不生效

### ISSUE THREAD

**Issue by 745819123** [KubeOperator/KubePi#22]
**KubePi 版本**
v1.1.1

**Kubernetes 版本**
v1.19.9

**Bug 描述**
二进制启动kubepi-server时，flag不生效

**Bug 重现步骤(有截图更好)**
1.
![image](https://user-images.githubusercontent.com/10809565/139414069-ec407ab9-e288-4155-9852-43783ba4e76c.png)

**Comment by wanghe-fit2cloud** [comment]
最新版本已解决。
