### ISSUE TITLE
[Feature]数据项内容被撑到页面之外，没有适配页面宽度换行显示。

### ISSUE THREAD

**Issue by zhangle3** [KubeOperator/KubePi#23]
在显示较长数据项内容时，建议能够适配页面，将内容根据浏览器窗口大小，换行显示；
例如，在查看Secrets的flannel-token的数据里的token时，由于token值过长，值区域被拉长，
需要拖动才能查看完整的数据。官方的dashboard可以在适配页面宽度，换行显示。

**Comment by wanghe-fit2cloud** [comment]
最新版本已解决
