### ISSUE TITLE
Service暴露出的随机端口不显示[Bug]

### ISSUE THREAD

**Issue by torans** [KubeOperator/KubePi#24]
**KubePi 版本**
v1.1.1

**Kubernetes 版本**
v1.20.0

**Bug 描述**
通过kubectl service暴露出来的随机端口在UI中没有显示出来

**Bug 重现步骤(有截图更好)**
1.
<img width="721" alt="WechatIMG192" src="https://user-images.githubusercontent.com/11582281/139617167-606fdf71-1123-4ad3-a573-19522fceb0c9.png">
<img width="1161" alt="WechatIMG193" src="https://user-images.githubusercontent.com/11582281/139617181-fed1fdd9-eaef-45da-befb-b7b5a672a94f.png">

2.
3.

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。我们会在下个版本优化NodePort端口显示问题

**Comment by wanghe-fit2cloud** [comment]
已解决，请使用最新版本。
