### ISSUE TITLE
[Bug]控制台报错500

### ISSUE THREAD

**Issue by satsuki887** [KubeOperator/KubePi#25]
**KubePi 版本**
v1.1.0

**Kubernetes 版本**
v1.18.15-ko1

**Bug 描述**
控制台所有页面都报500错误。

**Bug 重现步骤(有截图更好)**
1.状态为正常，可以看到相关概览信息，但点击控制台进去后，所有页面都是500错误。
![image](https://user-images.githubusercontent.com/50507743/139635637-6ae9fa7a-3172-4a6f-a58f-5a0e3263c564.png)
![image](https://user-images.githubusercontent.com/50507743/139635663-1b4d930c-d99b-4b07-b728-a000236ee32e.png)

2.单独用docker起pi容器，是同样的情况，也试过分别使用token和config文件来导入信息，都报错。

**Comment by wanghe-fit2cloud** [comment]
问题已收到，感谢反馈。

**Comment by wanghe-fit2cloud** [comment]
已解决，请使用最新版本。
