### ISSUE TITLE
[Feature]pod详情建议增加显示CPU及内存使用率

### ISSUE THREAD

**Issue by zhangle3** [KubeOperator/KubePi#26]
查看pod详情，建议增加显示CPU及内存使用率，如dashboard中那样，最好能显示一段时间的趋势图，对解决因OOMKill而重启的问题很有帮助。
<img width="260" alt="resource_used" src="https://user-images.githubusercontent.com/91599359/139644404-fe7b25d5-f318-4278-97f0-19b692673b8b.png">

**Comment by wanghe-fit2cloud** [comment]
好的，感谢反馈。
我们会在后续版本中做出优化。

**Comment by wanghe-fit2cloud** [comment]
最新版本已支持Pod列表显示CPU和内存使用率
