### ISSUE TITLE
希望支持用户行为审计功能

### ISSUE THREAD

**Issue by linl12138** [KubeOperator/KubePi#27]
当前平台权限管理是将K8s资源分配给不同用户，但对于普通用户在平台的操作并没有提供记录审查的功能（以及可能存在的复核流程），建议在后续版本补足这一功能。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。
我们会在下个版本增加用户操作日志功能

**Comment by wanghe-fit2cloud** [comment]
v1.3.0版本已支持日志审计功能
