### ISSUE TITLE
四个链接的字体太小了，都看不见是啥，建议优化为正常人类效果[Feature]

### ISSUE THREAD

**Issue by gzlisanshao** [KubeOperator/KubePi#28]
**请描述您的需求或者改进建议.**
如图：
![image](https://user-images.githubusercontent.com/47784139/140277748-c9cfb9b9-4c58-4f3d-94f8-e425d7191f58.png)
![Uploading image.png…]()

**Comment by wanghe-fit2cloud** [comment]
![image](https://user-images.githubusercontent.com/46734380/140278395-dd780ff0-add7-4e3c-8775-901febcb3bd5.png)
