### ISSUE TITLE
建议增加资源限额信息[Feature]

### ISSUE THREAD

**Issue by gzlisanshao** [KubeOperator/KubePi#29]
**请描述您的需求或者改进建议.**
包括集群资源限额信息：Node Allocatable Resource  Node Capacity - Kube-reserved - system-reserved - eviction-threshold 等等
namespaces限额信息 ，包括Limits和requests
pod限额信息 ，包括Limits和requests
至少能在列表上显示，能编辑修改就更好了
目的是一目了然看到资源分配情况，能排序

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。
上述需求我们会在后续版本会做出优化。

**Comment by wanghe-fit2cloud** [comment]
最新版本已支持在详情页显示资源、配额等更多内容
