### ISSUE TITLE
[Bug]集群授权

### ISSUE THREAD

**Issue by hanshuishi** [KubeOperator/KubePi#32]
**KubePi 版本**

1.2.0
**Kubernetes 版本**

**Bug 描述**
集群授权创建用户时，用户名称不能搜索

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。在后面版本会针对上述反馈做出优化

**Comment by wanghe-fit2cloud** [comment]
v1.2.1版本已增加选择框搜索功能
