### ISSUE TITLE
版本: v1.1.2 浏览器加载错误

### ISSUE THREAD

**Issue by piano-wow** [KubeOperator/KubePi#33]
**KubePi 版本**
版本: v1.1.2

**Kubernetes 版本**
版本: v1.22.2

**Bug 描述**
使用docker方式安装的kubepi，使用nginx代理它的dashboard，通过https进行访问，首页能正常访问并登录。
添加集群后，点击“控制台“进行登录，Chrome和edge浏览器大概率报503错误，firefox正常。

**Bug 重现步骤(有截图更好)**
1.
![image](https://user-images.githubusercontent.com/35907674/141256760-e0d8ba15-7a6f-4aa3-ac2b-3a8d4b3bee73.png)
2.
![image](https://user-images.githubusercontent.com/35907674/141256827-dcda2ecc-372f-4a97-98c3-1226916f9225.png)

**Comment by wanghe-fit2cloud** [comment]
我们在本地开发环境没有复现该问题，建议您升级到最新版本。

**Comment by piano-wow** [comment]
这是来自QQ邮箱的自动回复邮件。来信已收到！

**Comment by wanghe-fit2cloud** [comment]
也可以加入我们的微信交流群来讨论相关问题
