### ISSUE TITLE
[Bug]kubepi的集群列表，分页显示问题

### ISSUE THREAD

**Issue by pulse-line-dev** [KubeOperator/KubePi#34]
**KubePi 版本**
1.2.0

**Kubernetes 版本**
所有

**Bug 描述**

kubepi的集群列表那，分页展示有问题

**Bug 重现步骤(有截图更好)**
1.加了11个集群，没有跳转至第2页的地方？
<img width="1765" alt="企业微信截图_3aefe77d-5552-4f15-ae7f-e3f415a3de05" src="https://user-images.githubusercontent.com/52453702/141274655-a1dcfcfe-139a-4cc6-95de-28798aea3552.png">

<img width="1747" alt="企业微信截图_ecdf5e69-99fd-4dd7-aa2c-49c9baec2a4f" src="https://user-images.githubusercontent.com/52453702/141274668-0814648d-5e8d-4660-9a38-f2bf5988e7d7.png">

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在下版本修复该问题

**Comment by Aaron3S** [comment]
fixed on https://github.com/KubeOperator/KubePi/commit/9b35e720a93cb3056d545efa4759628fda803170

**Comment by wanghe-fit2cloud** [comment]
v1.2.1版本已修复。
