### ISSUE TITLE
[Feature]个别页面的名称显示不完整

### ISSUE THREAD

**Issue by wojiushixiaobai** [KubeOperator/KubePi#37]
**请描述您的需求或者改进建议.**
![image](https://user-images.githubusercontent.com/24326988/142796483-1078e97f-a6a9-465d-beb9-9297e91090d9.png)

看看是否需要优化下，比如可以让用户自动调整长度，或者换行等。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。我们会在下个版本针对该问题做出优化。

**Comment by wanghe-fit2cloud** [comment]
v1.3.0版本已修复
