### ISSUE TITLE
POD部分终端无法进入

### ISSUE THREAD

**Issue by Aaron-kk** [KubeOperator/KubePi#4]
提示如下：
OCI runtime exec failed: exec failed: container_linux.go:349: starting container process caused "exec: \"sh\": executable file not found in $PATH": unknown

建议优化，可手动或自动选择可用解释器

**Comment by wanghe-fit2cloud** [comment]
可以的，之后版本支持选择解释器

**Comment by wanghe-fit2cloud** [comment]
v3.11.0 版本已支持自定义解释器
