### ISSUE TITLE
[Feature] 如果kubepi 部署在k8s 集群上，能否默认添加本集群到 kubepi 管理？

### ISSUE THREAD

**Issue by tanguofu** [KubeOperator/KubePi#40]
**请描述您的需求或者改进建议.**
请问当前版本如果要实现 部署kupepi的时候， 默认添加当前部署集群，需要怎么操作呢？

**Comment by wanghe-fit2cloud** [comment]
参考官方文档

kubepi 部署: https://kubeoperator.io/docs/kubepi/install/
导入集群: https://kubeoperator.io/docs/kubepi/cluster/

**Comment by tanguofu** [comment]
> 参考官方文档
> 
> kubepi 部署: https://kubeoperator.io/docs/kubepi/install/ 导入集群: https://kubeoperator.io/docs/kubepi/cluster/

感谢回复， 页面操作我知道的，我想请问 如果通过脚本 或者命令自动化 怎么实现呢？

**Comment by wanghe-fit2cloud** [comment]
12月版本会将KubeOperator和KubePi整合到一起。等集群创建成功之后，不再需要工具中启用KubePi，直接在集群列表就可以访问KubePi Dashboard

**Comment by tanguofu** [comment]
> 12月版本会将KubeOperator和KubePi整合到一起。等集群创建成功之后，不再需要工具中启用KubePi，直接在集群列表就可以访问KubePi Dashboard

额 现阶段 或者 我们只需要用kubepi 有啥 推荐的办法不？

**Comment by wanghe-fit2cloud** [comment]
![image](https://user-images.githubusercontent.com/46734380/143819912-f03e1096-b0e6-41a8-99b2-565218dd0788.png)

sudo docker run --privileged -d --restart=unless-stopped -p 80:80 kubeoperator/kubepi-server

**Comment by tanguofu** [comment]
> ![image](https://user-images.githubusercontent.com/46734380/143819912-f03e1096-b0e6-41a8-99b2-565218dd0788.png)
> 
> sudo docker run --privileged -d --restart=unless-stopped -p 80:80 kubeoperator/kubepi-server

额 部署我知道的 我是想请教 怎么实现自动的注册集群到 kubepi里面， 而不是用页面操作的方式。

非常感谢

**Comment by tanguofu** [comment]
@wanghe-fit2cloud  这里有什么好的实践 推荐么？ 谢谢

**Comment by wanghe-fit2cloud** [comment]
可以将k8s集群导入到KubeOperator中（最新版本已经集成了KubePi）
在KubeOperator的集群列表就可以直接跳转到KubePi（会将集群自动添加到KubePi中，不需要在KubePi中再次添加集群）

![image](https://user-images.githubusercontent.com/46734380/146734217-b9d4560e-175d-4099-9905-17be27c4877e.png)

**Comment by wanghe-fit2cloud** [comment]
KubeOperator 官方文档：https://kubeoperator.io/docs/installation/install/
