### ISSUE TITLE
[Bug] 仓库应用无法同步

### ISSUE THREAD

**Issue by xlkness** [KubeOperator/KubePi#41]
**KubePi 版本**
1.2.0

**Kubernetes 版本**
1.20

**Bug 描述**
Chart仓库配置了自带的ChartMusuem，推送应用后无法查看到更新

**Bug 重现步骤(有截图更好)**
1.添加仓库，推送应用到仓库
2.查看应用，无法找到对应更新
3.再次配置仓库，将认证改为无，查看应用可以找到更新

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们会在后续版本中增加同步仓库功能

**Comment by wanghe-fit2cloud** [comment]
v1.3.0版本已经支持chart仓库同步
