### ISSUE TITLE
[Bug]前端单独运行以后，提示Proxy error  (Econnreset)

### ISSUE THREAD

**Issue by sunlibo111111** [KubeOperator/KubePi#42]
**KubePi 版本**

**Kubernetes 版本**

**Bug 描述**

前端单独运行以后，提示Proxy error: Could not proxy request /kubepi/api/v1 from localhost:4300 to http://localhost:80 (Econnreset)

**Bug 重现步骤(有截图更好)**
![QQ图片20211206160145](https://user-images.githubusercontent.com/23656618/144810826-16ec801b-d30b-4ef4-9df3-a2d14de40059.png)

**Comment by wanghe-fit2cloud** [comment]
需要启动后端服务

**Comment by sunlibo111111** [comment]
后端服务已经启动，运行几分钟后刷新会出现提示

**Comment by sunlibo111111** [comment]
前端发布后，放到cmd/server/web 下运行后端访问是可以的

**Comment by sunlibo111111** [comment]
> 需要启动后端服务

后端服务已经启动，运行几分钟后刷新会出现提示，但是数据是可以出来的。如果把，前端发布后放到cmd/server/web 下运行后端直接访问http://localhost:80 是可以的。
