### ISSUE TITLE
[Bug]升级之后控制面板异常

### ISSUE THREAD

**Issue by topicgit** [KubeOperator/KubePi#43]
**KubePi 版本**
1.3.0

**Kubernetes 版本**

1.18.4
**Bug 描述**
按照文档升级kubepi ，控制面板中有一个集群异常显示，无法控制，请问应该如何排查？

**Bug 重现步骤(有截图更好)**
![image](https://user-images.githubusercontent.com/11975460/145710625-5b8eff57-cf47-42fd-95cf-cdcfc3c16899.png)

排查日志也没有什么错误
![image](https://user-images.githubusercontent.com/11975460/145710649-496b27cc-e916-4da7-8970-6de58c20460f.png)

**Comment by wanghe-fit2cloud** [comment]
重新添加错误状态的集群，观察是否有错误日志

**Comment by topicgit** [comment]
> 重新添加错误状态的集群，观察是否有错误日志

感谢 🙏 ，找到原因了，是因为TKE需要绑定一个域名去访问apiserver，之前手动配置再容器，升级重新创建容器后未配置host绑定导致.
