### ISSUE TITLE
[Question]请问创建的ReplicationController在哪儿能看到啊

### ISSUE THREAD

**Issue by lixh00** [KubeOperator/KubePi#45]
**请描述您的问题.**
如题所述，似乎没有找到RC的列表，只能在pods里面看到有pods在运行

**Comment by wanghe-fit2cloud** [comment]
kubepi创建workload，当前版本还不支持rc

**Comment by lixh00** [comment]
> kubepi创建workload，当前版本还不支持rc

原来如此，有支持的计划嘛？

**Comment by wanghe-fit2cloud** [comment]
建议使用Deployment来取代ReplicationController

**Comment by lixh00** [comment]
> 建议使用Deployment来取代ReplicationController

好的嘞！！

**Comment by lixh00** [comment]
对了，还有个小问题，这玩意儿对K3s的兼容有一点点不好，在创建`Ingress`的时候，必须手动把`apiVersion: networking.k8s.io/v1beta1`改成`apiVersion: networking.k8s.io/v1`，不然无法创建。

**Comment by wanghe-fit2cloud** [comment]
> 对了，还有个小问题，这玩意儿对K3s的兼容有一点点不好，在创建`Ingress`的时候，必须手动把`apiVersion: networking.k8s.io/v1beta1`改成`apiVersion: networking.k8s.io/v1`，不然无法创建。

问题已收到。

**Comment by lixh00** [comment]
> 问题已收到。

好的嘞，您辛苦了！

**Comment by lixh00** [comment]
对了，默认后端不写好像也会无法创建
