### ISSUE TITLE
[Bug]通过可视化创建deployment时选择拉取的Secrets无效,重新编辑也无效只有通过手动修改yaml文件

### ISSUE THREAD

**Issue by cowardmrx** [KubeOperator/KubePi#46]
**KubePi 版本**
v1.3.0

**Kubernetes 版本**
v1.21.7+k3s1

**Bug 描述**
[Bug]通过可视化创建deployment时选择拉取的Secrets无效,重新编辑也无效只有通过手动修改yaml文件

**Bug 重现步骤(有截图更好)**
1.
![image](https://user-images.githubusercontent.com/74823020/145968202-fbb008b7-6104-4ed1-800c-5a1b78755e21.png)

2.
![image](https://user-images.githubusercontent.com/74823020/145968359-25fbdd9a-4c75-48cf-a9fa-88bc4151abdf.png)
![image](https://user-images.githubusercontent.com/74823020/145968518-14e10b93-24e0-482e-ac33-83db45716378.png)

3.
![image](https://user-images.githubusercontent.com/74823020/145968652-286316f3-db05-4824-956a-7b68361ccf71.png)

**Comment by ssongliu** [comment]
好的，问题已验证。
我们会在接下来版本中会修复该问题，感谢！

**Comment by ssongliu** [comment]
好的，问题已验证。
我们会在接下来版本中修复该问题，感谢！
