### ISSUE TITLE
[Question]编辑，伸缩副本报错

### ISSUE THREAD

**Issue by wojiushixiaobai** [KubeOperator/KubePi#49]
**请描述您的问题.**
![image](https://user-images.githubusercontent.com/24326988/146922126-26069c86-4bc4-445f-85c3-08e59fa35498.png)
![image](https://user-images.githubusercontent.com/24326988/146922222-c86e50ba-2841-414d-b4c7-37e19aebb504.png)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，麻烦提供一下kubepi版本和k8s集群版本信息。

**Comment by wojiushixiaobai** [comment]
已经解决。
