### ISSUE TITLE
[Bug]通过kubeconfig的方式加入集群超时

### ISSUE THREAD

**Issue by withlin** [KubeOperator/KubePi#53]
**KubePi 版本**
v1.13

**Kubernetes 版本**
v1.20.6

**Bug 描述**
Kubepi 运行了一段时间 加入集群是没有问题的，但是今天，通过kubeconfig的方式加入集群超时。 因为着急用，就没有细看，所以重启了，就能加入集群了

**Bug 重现步骤(有截图更好)**
![image](https://user-images.githubusercontent.com/22409551/148038531-aa7021b0-c3f4-4fe7-a144-587f3df41838.png)

**Comment by wanghe-fit2cloud** [comment]
超时是调用k8s api导致的，有没有注意k8s集群状态？

**Comment by withlin** [comment]
@wanghe-fit2cloud 正常的～

**Comment by wanghe-fit2cloud** [comment]
好的，我们本地也复现一下该问题吧

**Comment by mengerwei** [comment]
我也有同样的问题，第一次添加测试集群运行15天，添加预发布集群是出现超时；今天是预发布运行了一周，我添加生产的集群，一样是超时。不管我重启kubepi还是本地安装kubepi添加生产集群都不行。我觉得后台有api和飞致在做调用注册。

**Comment by withlin** [comment]
@wanghe-fit2cloud  复现： 只要加入一个错误的集群，第二次加入就会百分百超时。
