### ISSUE TITLE
[Feature] 考虑加入debug功能

### ISSUE THREAD

**Issue by withlin** [KubeOperator/KubePi#54]
**请描述您的需求或者改进建议.**
现在是容器都很精简，当需要调试的时候，就要在里面安装各种工具，非常不方便，如果可以，可以做一个debug的入口。利用docker的namespace 和cgroup的方式带着工具debug目标pod。

#### 做法
* 在容器那一列增加一个菜单，就叫debug-ternimal的选项。
* 点击debug-ternimal，可以传入debug镜像的表单(如果有条件可以支持私有的register)，先支持dockerhub的吧。
* 然后点击确定，1.找到pod所在的node 2. 在该node启动一个pod 3. 和目标的pod共享namespce和cgroup。 后面交互一样的。

**Comment by withlin** [comment]
![image](https://user-images.githubusercontent.com/22409551/148039682-98d48d93-858c-40a6-955c-8049a31f9a90.png)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。
我们在后续版本中考虑一下该需求。

**Comment by withlin** [comment]
@wanghe-fit2cloud  why close?

**Comment by wanghe-fit2cloud** [comment]
后续版本会考虑。
