### ISSUE TITLE
pod日志下载给什么权限？

### ISSUE THREAD

**Issue by mengerwei** [KubeOperator/KubePi#57]
我是运维，kubepi想给研发人员使用，因为人员较多，防止大家对pod有操作权限，我只想给readonly权限，让他们看日志即可，目前只读权限给了，但是发现下载日志权限没有，希望可以指点下？

我的只读权限摸版如下：
![image](https://user-images.githubusercontent.com/24802170/148199147-e46fa473-fea4-4d24-89e7-ab5dbef9082c.png)

进入pod下载当天的日志提示没权限forbend，请问我还需要给什么权限？

**Comment by wanghe-fit2cloud** [comment]
可以先手动创建rbac关系来确定具体需要的权限，然后再通过kubepi来绑定。
