### ISSUE TITLE
kubepi项目可以支持飞书、邮件？

### ISSUE THREAD

**Issue by mengerwei** [KubeOperator/KubePi#58]
**请描述您的需求或者改进建议.**
kubepi被定义为k8s集群管理服务，涉及到集群管理，肯定会有人员关系和集群关系匹配问题；
第一步：开账号。目前不支持邮箱、飞书、钉钉，开账号都需要手动，还需要同步账号密码很难；或者弄个注册功能也很方便，以逸待劳。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。
后续版本会考虑增加上述企业级功能。
