### ISSUE TITLE
[Feature] 考虑加入容器文件浏览的功能

### ISSUE THREAD

**Issue by xmapst** [KubeOperator/KubePi#59]
**请描述您的需求或者改进建议.**
具体参考[kubefilebrowser](https://github.com/xmapst/kubefilebrowser)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，我们已记录该需求。

**Comment by Blue-Skyer** [comment]
Hello, We notice that xmapst (https://github.com/xmapst) proposed the feature, but the code relies on the GitHub project (https://github.com/xmapst/kubefilebrowser), in which xmapst is one of the contributors. We would like to highlight this as a unpleasant "self-promotion" (promoting the use of a project without mentioning that xmapst is associated with the project).
Regards, Blue Skyer.

**Comment by wanghe-fit2cloud** [comment]
v1.5.0 版本已支持

**Comment by xmapst** [comment]
谢谢您的抄袭

**Comment by xmapst** [comment]
> 请问有修复的 PR 链接或者 commit 链接么？我想学习一下 ; P

[https://github.com/xmapst/kubefilebrowser.git](https://github.com/xmapst/kubefilebrowser.git)
