### ISSUE TITLE
suggest

### ISSUE THREAD

**Issue by Aaron-kk** [KubeOperator/KubePi#6]
几点体验优化建议
1、面板列表的排序功能
2、选择namespace时排序或搜索
3、pod状态显示Running、Terminating等
4、容器日志过滤/下载
5、管理operator的资源

**Comment by wanghe-fit2cloud** [comment]
收到，以上建议会在后面版本中优化

**Comment by wanghe-fit2cloud** [comment]
建议将KubePi升级到最新版本
