### ISSUE TITLE
[Bug]service里边对应的pods显示时出错

### ISSUE THREAD

**Issue by bibichong** [KubeOperator/KubePi#61]
**KubePi 版本**
1.3.0（最新master构建，修改过Makefile（npm 允许root）和 init-kube.sh 脚本内容）
![image](https://user-images.githubusercontent.com/25101581/149056618-8526e2f0-9a26-4fce-8f5e-4a4b7225e9b6.png)

**Kubernetes 版本**
v1.20.6 |  rancher 2.5.8安装的集群

**Bug 描述**
service里边的pod元素因为无法拉取pod的某些信息，导致load的转圈图一直存在。
![image](https://user-images.githubusercontent.com/25101581/149056656-c3befbe5-30ac-456d-b4c6-56e45a673ec2.png)
![image](https://user-images.githubusercontent.com/25101581/149056663-687cfd09-d2ae-47bf-9ba0-e910bcd16936.png)
![image](https://user-images.githubusercontent.com/25101581/149056679-34216c11-8681-428c-9bd5-d67fe32110b2.png)

是我自己的配置的问题，还是都有这个问题啊？

**Comment by ssongliu** [comment]
本地已复现该问题，感谢反馈，将在下个版本完成修复。
