### ISSUE TITLE
[Feature] 增加一键批量伸缩的功能

### ISSUE THREAD

**Issue by CaoYunzhou** [KubeOperator/KubePi#62]
**建议在这里对deploy,sts增加一键批量伸缩的功能**
![image](https://user-images.githubusercontent.com/28099773/150461558-606208cc-a10b-4166-808f-4738ef8cd291.png)

批量全选中对pods进行批量伸缩
当namespace中有大量pods需要一键伸缩到0个副本，需要一个一个手工操作

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。
我们会在后面版本增加该功能。

**Comment by wanghe-fit2cloud** [comment]
v1.4.1版本已增加批量伸缩功能。
