### ISSUE TITLE
[Bug] RKE 创建集群，授权报错：create common user failed: csr approve time out

### ISSUE THREAD

**Issue by Castieler** [KubeOperator/KubePi#65]
**KubePi 版本**
v1.4.0
**Kubernetes 版本**
v1.19.6 版本，通过 rancher 下 rke 部署

**Bug 描述**
集群授权报错：create common user failed: csr approve time out ,30 sec

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by wanghe-fit2cloud** [comment]
好的，问题已收到，感谢反馈。

我们本地的开发测试环境用集群是通过 [KubeOperator](https://github.com/KubeOperator/KubeOperator) 创建的集群，你可以在你们本地环境来部署集群。

**Comment by bibichong** [comment]
这个问题我之前遇到过，搜索发现问题是rancher创建集群的模板里没给controller指定根证书，导致csr无法创建。
![image](https://user-images.githubusercontent.com/25101581/156485811-1134aa50-72e9-46fe-8f31-fc1b4f5dad6f.png)
加上这个参数就好了。你看看你的是不是也没加这个。
