### ISSUE TITLE
[Feature]应用商店抽离到cluster级别

### ISSUE THREAD

**Issue by withlin** [KubeOperator/KubePi#66]
**请描述您的需求或者改进建议.**
### 背景
现在的kubePi的应用商店是在每个cluster里面的，现在想抽到集群外面，需要做到部署应用的时候，可以选择部署到的集群下的某个namespace里面

### 用户故事
现在有100多个k8s集群，需要通过应用商店部署到这100多个集群中，由于kubepi的设计限制，我觉得应该抽到最外层的菜单来方便部署cluster级别的应用商店。

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。
我们会在后续版本中考虑上述需求。

**Comment by zhengkunwang223** [comment]
> **请描述您的需求或者改进建议.**
> 
> ### 背景
> 现在的kubePi的应用商店是在每个cluster里面的，现在想抽到集群外面，需要做到部署应用的时候，可以选择部署到的集群下的某个namespace里面
> 
> ### 用户故事
> 现在有100多个k8s集群，需要通过应用商店部署到这100多个集群中，由于kubepi的设计限制，我觉得应该抽到最外层的菜单来方便部署cluster级别的应用商店。

请描述具体的需求 比如什么应用安装在几个集群中 应用的参数是什么 我们会根据具体的需求考虑要不要做
