### ISSUE TITLE
[Bug] 导入 EKS 创建的集群无法分配用户权限，csr approve timeout

### ISSUE THREAD

**Issue by UnknowViewer** [KubeOperator/KubePi#70]
**KubePi 版本**
v1.4.1

**Kubernetes 版本**
v1.21.5-eks-bc4871b

**Bug 描述**
导入通过AWS EKS创建的Kubernetes集群后，使用内置admin账号登录可以访问，但是无法分配给通过LDAP同步的账号访问权限，授权时提示 csr approve timeout
<img width="1150" alt="Screen Shot 2022-03-01 at 16 47 50" src="https://user-images.githubusercontent.com/14183726/156135895-109658b5-7134-468d-ac48-ba7faa459a3b.png">

**Bug 重现步骤(有截图更好)**
1. 
2.
3.

**Comment by wanghe-fit2cloud** [comment]
已知问题。
原因是因为 eks 在开源 k8s 版本基础之上有自定义认证授权等逻辑，我们已尝试在本地修改该问题。

**Comment by Chinaxiang** [comment]
这个问题什么时候修复？

**Comment by wanghe-fit2cloud** [comment]
由于 EKS 在开源 K8s 基础之上自定义了认证授权等逻辑，KubePi 暂时将不会针对 EKS 集群进行适配。
