### ISSUE TITLE
[Bug] 集群名称中包含特殊字符导致无法进入集群页面

### ISSUE THREAD

**Issue by UnknowViewer** [KubeOperator/KubePi#71]
**KubePi 版本**
v1.4.1

**Kubernetes 版本**
v1.81.0

**Bug 描述**
导入集群时填写集群名称可以填 & % 等在URL中需要被转译的特殊字符，集群可以被正常创建，但是点击进入集群详情时跳转的URL就会被集群名称中的特殊字符截断导致跳转失败

**建议解决方案**
1. 在集群名称的输入框内做限制，禁止输入与URL跳转冲突的特殊字符
2. 在前端对集群名称做转译
3. 在后端对集群访问地址做编码

**Bug 重现步骤(有截图更好)**
1. 导入集群，集群名称填写 a&b，可以被正常创建
4. 访问集群，报HTTP 500的错误
<img width="295" alt="image" src="https://user-images.githubusercontent.com/14183726/156287715-41a1760e-a827-4032-aa73-e92e6c64ed04.png">
<img width="801" alt="image" src="https://user-images.githubusercontent.com/14183726/156287726-4582df67-316e-4754-ae36-158d7b318677.png">

**Comment by wanghe-fit2cloud** [comment]
问题已收到，感谢反馈。

**Comment by wanghe-fit2cloud** [comment]
v1.4.2 版本已修复。
