### ISSUE TITLE
[Feature]只读用户是否可以开放容器日志权限

### ISSUE THREAD

**Issue by chenruiyingry** [KubeOperator/KubePi#72]
最新版kubePi中发现只读权限看不到容器运行状态，也无法查看容器日志，请问是否可以实现以下功能：开发人员无法修改配置、数量等（即只读），且无法访问终端，只允许查看容器状态、数量，以及容器日志。这样方便开发人员查阅容器日志。谢谢。

**Comment by wanghe-fit2cloud** [comment]
只读用户可以查看容器状态和数量，不能访问终端和日志
