### ISSUE TITLE
[Bug]用户密码不支持输入下划线 _

### ISSUE THREAD

**Issue by wujianqinjian** [KubeOperator/KubePi#74]
**KubePi 版本**
ko 版本： v1.22.6-ko1

**Kubernetes 版本**
1.22

**Bug 描述**
用户 修改密码时，好像在ko和kubupi中都有这个现象，密码：aa__123!**  无法通过

**Bug 重现步骤(有截图更好)**
1.
2.
3.

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，在接下来版本会修复该问题。

**Comment by wanghe-fit2cloud** [comment]
v1.5.0 版本已修复
