### ISSUE TITLE
[Question]ngx 反代 kubepi 配置

### ISSUE THREAD

**Issue by youzibaby** [KubeOperator/KubePi#75]
跨域设置 Access-Control-Allow-Credentials true 无用， cookie过不去
求一份反代正确配置

**Comment by wanghe-fit2cloud** [comment]
KubePi 没有使用 nginx 作为反向代理服务器。

**Comment by seaurching** [comment]
> KubePi 没有使用 nginx 作为反向代理服务器。

这个意思是用nginx反向代理kubepi怎么配置？我记得官方之前有这个内容，是取消了吗
