### ISSUE TITLE
k8s版本名称长，在页面上显示不完整[Bug]

### ISSUE THREAD

**Issue by Casent** [KubeOperator/KubePi#80]
<img width="578" alt="image" src="https://user-images.githubusercontent.com/24560273/164578658-d50aeba3-38a6-4180-8140-86b1788b58e4.png">

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，后续版本修复。

**Comment by wanghe-fit2cloud** [comment]
v1.5.0 版本已修复
