### ISSUE TITLE
配置集群存储：选择vsphere类型时，希望可以自动获取到集群相关的信息

### ISSUE THREAD

**Issue by szzylph** [KubeOperator/KubePi#81]
配置集群存储：选择vsphere类型时，希望可以自动获取到集群相关的信息
![image](https://user-images.githubusercontent.com/57162724/164582163-07a1ac9b-f724-44e4-9231-51f62e98fafa.png)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，在后续版本会针对上述问题作出优化。

**Comment by wanghe-fit2cloud** [comment]
最新版本已支持
