### ISSUE TITLE
[Bug]kubepi控制台修改了calico-typha策略怀疑导致数据错误

### ISSUE THREAD

**Issue by xu-xiang** [KubeOperator/KubePi#82]
**KubePi 版本**
版本: v3.14.0

**Kubernetes 版本**
    v1.22.6-ko1

**Bug 描述**
通过kubepi控制台修改了calico-typha的节点策略，保存提交后，运行却报错
```
Failed | Warning | kube-system | Error: configmap "kubernetes-services-endpoint" not found | Pod / calico-typha-5bd4447f74-8cfqs
```
怀疑是控制台保存中导致了配置文件数据错误

**Bug 重现步骤(有截图更好)**
1. 修改calico-typha的节点策略
2.提交后，calico-typha无法启动且报错如上
![911650970295_ pic](https://user-images.githubusercontent.com/12231426/165285754-ee3f009c-7e28-4a33-867c-5c32d6743be0.jpg)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。

**Comment by wanghe-fit2cloud** [comment]
v1.5.0 版本已修复
