### ISSUE TITLE
[Bug] 自定义授权终端和日志异常

### ISSUE THREAD

**Issue by k8sre** [KubeOperator/KubePi#84]
**KubePi 版本**
1.4.2

**Kubernetes 版本**
1.22.3

**Bug 描述**
使用自定义授权后，Pod中有两个及以上容器可以访问终端和日志，Pod中只有一个容器的，终端和日志菜单是灰色的，不能点击进入，但是直接把Url改为Pod中只有一个容器的终端Url，是可以访问终端的。

**Bug 重现步骤(有截图更好)**
1.
<img width="628" alt="image" src="https://user-images.githubusercontent.com/35365219/167762514-c2b2c0ef-4e93-4897-9400-8fcca913062f.png">

2.
<img width="647" alt="image" src="https://user-images.githubusercontent.com/35365219/167762533-81534dc9-f335-4c09-8ee7-e866ddc8617c.png">

3.

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。

**Comment by wanghe-fit2cloud** [comment]
“使用自定义授权后，...”
这里授权到用户的具体是什么权限。

**Comment by k8sre** [comment]
<img width="735" alt="image" src="https://user-images.githubusercontent.com/35365219/168503598-87c1e24a-5128-419d-b55e-90d577a8c084.png">

**Comment by ssongliu** [comment]
> <img alt="image" width="735" src="https://user-images.githubusercontent.com/35365219/168503598-87c1e24a-5128-419d-b55e-90d577a8c084.png">

您好，反馈的问题在于 1.4.2 版本进入终端和日志判断都是以 * 权限来判断，在 1.5.0 版本中，我们优化了这部分权限判断，其中
    1. 进入终端需要 pods/exec 的 create 权限；
    2. 查看日志需要 pods/log 的 get 权限。
 感谢反馈！
