### ISSUE TITLE
[Bug] k8s 集群升级后，从dashboard 按钮跳转到kubepi中，集群名称一样的情况下出错连接不上新集群

### ISSUE THREAD

**Issue by yuby1977** [KubeOperator/KubePi#85]
**KubePi 版本**
1.4.2 
**Kubernetes 版本**
1.22.6 

**Bug 描述**

k8s 集群升级后，从dashboard 按钮跳转到kubepi中，集群名称一样的情况下出错连接不上新集群

**Bug 重现步骤(有截图更好)**
1. 通过ko 把k8s 从1.20.10 升级到1.22.6 
2. 原k8s 集群名称和原来的一样
3. 从dashboard 按钮跳转到kubepi中 报500 错误
4. 进入到kubepi 中，在集群总览中发现集群信息还是原来的1.20.10 的信息
5. 删除原来集群信息，重新从dashboard 按钮跳转到kubepi中正常

**Comment by wanghe-fit2cloud** [comment]
感谢反馈，后续版本修改该问题。
