### ISSUE TITLE
[Feature]对于kubepi的一些建议

### ISSUE THREAD

**Issue by zhangye151** [KubeOperator/KubePi#87]
**对于kubepi的一些建议：**

1. 希望加入Endpoints表单创建功能，部署外部就不用写yaml文件了，对于新手和轻度用户很方便。或是在创建service时能直接关联编辑Endpoints，当然能直接关联Ingresses编辑更好了。
2. 希望加入在修改Deployments时也能有关联编辑。在创建Deployments的能直接创建service，并有关联编辑；但是修改Deployments却没有service关联编辑，当然能直接关联Ingresses编辑更好了。
3. 希望加入单节点环境自动添加节点功能，现在的情况是每次重启机就要重新添加节点，不想复制实在不想复制koten啊。
4. 希望加入浅色主题

**Comment by wanghe-fit2cloud** [comment]
建议3，详细讲一下呢

**Comment by zhangye151** [comment]
![image](https://user-images.githubusercontent.com/92865459/170645855-254ac716-f87b-420e-aeef-400002b76c78.png)
若是断电重启，集群就没有了，必须重新添加集群

**Comment by wanghe-fit2cloud** [comment]
因为你部署服务没有持久化导致的吧

**Comment by zhangye151** [comment]
额…………

**Comment by wanghe-fit2cloud** [comment]
v1.6.0 版本已经支持 Endpoints 表单创建功能

**Comment by wanghe-fit2cloud** [comment]
编辑 Deployment 时关联 Service 和浅色主题这两个需求不会添加到近期的迭代计划中
