### ISSUE TITLE
[Bug]应用市场中无法添加自签名Chart仓库

### ISSUE THREAD

**Issue by lengpucheng** [KubeOperator/KubePi#88]
**KubePi 版本**
v1.5.0

**Kubernetes 版本**
不涉及

**Bug 描述**
在应用市场中添加自签名Harbor的Chart仓库时，会弹气泡提示X509错误，并在气泡中附上仓库index页面的URL，使用浏览器的方式可以直接访问该URL并获取应用清单。

**Bug 重现步骤(有截图更好)**
1.应用市场-chart仓库-添加
2.输入自签名的Chart仓库URL，点击确定
![mmexport1653713229372](https://user-images.githubusercontent.com/56445668/170810500-568de884-9fb9-40d2-9ee3-90053fd5be79.jpg)

**Comment by wanghe-fit2cloud** [comment]
Get.
后续版本会适配自签名 Chart 仓库

**Comment by ssongliu** [comment]
感谢反馈，本地测试未能复现该问题
1. 请确认一下手动 helm add 是否可行？
2. 请提供一下 /Users/{用户名}/Library/Preferences/helm/{集群名}/repositories.yaml 文件；
3. 可以扫码添加一下交流群，方便更好的交流。

**Comment by lengpucheng** [comment]
> 

手动是可以的，因为手动考入了自签名证书，这里应该是没有忽略SSL证书警告导致的

**Comment by ssongliu** [comment]
![image](https://user-images.githubusercontent.com/73214554/170956521-522264a5-6034-4737-8dad-12264cf42c0f.png)
添加仓库已忽略证书校验，下图是本地添加的 https 仓库: 
![image](https://user-images.githubusercontent.com/73214554/170956798-bc2b39f8-d051-4370-b00f-5d192b51ee22.png)
![image](https://user-images.githubusercontent.com/73214554/170956858-750ad8e8-bc2b-461a-ba69-4cff669e8e6c.png)
