### ISSUE TITLE
[Bug]创建TLS证书类型Secrets失败

### ISSUE THREAD

**Issue by zhangye151** [KubeOperator/KubePi#89]
**KubePi 版本**
V1.5.1

**Kubernetes 版本**
v1.23.6+k3s1 

**Bug 描述**
Secrets，创建TLS证书，CRT与KEY的填写框是反的。

**Bug 重现步骤(有截图更好)**
1.
![image](https://user-images.githubusercontent.com/92865459/170851115-ab7925b0-f49f-4d6b-b8bc-d62d2ccbd679.png)

2.
![image](https://user-images.githubusercontent.com/92865459/170851120-d1a23592-b910-4dc8-b25e-5a62e5a43085.png)

因为这问题，HTTPS证书一直显示是traefik的不信任自签证书，我一直以为我的Traefik有问题，折腾了一周时间，一周时间

**Comment by wanghe-fit2cloud** [comment]
Get.
会发布新版本修复该问题。

**Comment by wanghe-fit2cloud** [comment]
v1.5.2 版本已修复.
