### ISSUE TITLE
[Bug] 部署完登录提示认证信息过期

### ISSUE THREAD

**Issue by ysicing** [KubeOperator/KubePi#9]
**KubePi 版本**
latest版本

**Kubernetes 版本**
无

**Bug 描述**
登录提示认证信息已过期，请重新登录

**Bug 重现步骤(有截图更好)**
docker run -d --restart=always -p 7080:80 kubeoperator/kubepi-server
![WeChat29c7abc14d24fa04745e6509b203bf7f](https://user-images.githubusercontent.com/8605565/134192271-054be43d-1ea1-401f-a92b-bb0b70c9c7bb.png)

![image](https://user-images.githubusercontent.com/8605565/134192433-1a5088c9-f47f-4123-813f-e2d55ee2f09a.png)

**Comment by wanghe-fit2cloud** [comment]
我们在 Chrome 和 Firefox 都验证了，没有复现该问题，你那边切换一下其他浏览器、刷新缓存再试一下。

如果还存在问题，可以在技术交流群一起讨论：
![wechat-group](https://kubeoperator.io/docs/img/wechat-group.png)
