### ISSUE TITLE
[Question]webkubectl自动断开

### ISSUE THREAD

**Issue by seaurching** [KubeOperator/KubePi#92]
在没有操作的时候，隔一段时间，webkubectl就无法使用了，按任意键没有反应。
kubectx 这个是什么怎么用？

**Comment by wanghe-fit2cloud** [comment]
https://github.com/kubeoperator/webkubectl

**Comment by seaurching** [comment]
> https://github.com/kubeoperator/webkubectl

@wanghe-fit2cloud 这个超时时间可以修改吗

**Comment by seaurching** [comment]
GOTTY_TOKEN_EXPIRES_DURATION设置这个可以解决
