### ISSUE TITLE
kubepi页面上查无法查看启动失败pods的提示日志

### ISSUE THREAD

**Issue by Casent** [KubeOperator/KubePi#93]
容器启动失败后，通过终端命令里面可以看到部分提示日志，但是在kubepi页面上是看不到日志
![image](https://user-images.githubusercontent.com/24560273/173349406-e7e7cae6-196e-43c1-9234-1fcc36ef05f0.png)

![image](https://user-images.githubusercontent.com/24560273/173349449-9f5db1e9-19ef-469a-b4ec-360e178ae326.png)

**Comment by wanghe-fit2cloud** [comment]
感谢反馈。

**Comment by wanghe-fit2cloud** [comment]
我们本地使用 nginx:latest 镜像创建 Deployment，终端和 kubepi 显示日志一致，未复现问题。
请问你那边有其他特殊设置吗？

![image](https://user-images.githubusercontent.com/46734380/173515905-2664ff08-dcab-4905-8b9b-eea380c8232a.png)

**Comment by Casent** [comment]
没有特殊的配置的，都是默认配置，nginx版本是：1.19.6 ，nginx配置错误类型是：location 代理一个不存在的域名。

```nginx
            location // {
                proxy_pass http://error-server:8080/;
            }
```
可以复现
