### ISSUE TITLE
[Bug] jwt鉴权失败

### ISSUE THREAD

**Issue by andy263** [KubeOperator/KubePi#96]
**KubePi 版本**
v1.5.3

**Kubernetes 版本**
any

**Bug 描述**

**Bug 重现步骤(有截图更好)**
1.登录时增加参数"authMethod":"jwt"，可以正常获得jwt token。
2.但调用其他api接口时，把token写到http header的Authorization字段里，仍然会返回401 Unauthorized
响应信息为
{
  "code": 401,
  "message": "jwt: token is empty",
  "success": false
}

**Comment by wanghe-fit2cloud** [comment]
Authorization: Bearer {token}

**Comment by zhengkunwang223** [comment]
> **KubePi 版本** v1.5.3
> 
> **Kubernetes 版本** any
> 
> **Bug 描述**
> 
> **Bug 重现步骤(有截图更好)** 1.登录时增加参数"authMethod":"jwt"，可以正常获得jwt token。 2.但调用其他api接口时，把token写到http header的Authorization字段里，仍然会返回401 Unauthorized 响应信息为 { "code": 401, "message": "jwt: token is empty", "success": false }

Authorization 需要Bearer开头 空格后跟token

**Comment by andy263** [comment]
感谢
