### ISSUE TITLE
[Question]集群如何替换新证书

### ISSUE THREAD

**Issue by frely** [KubeOperator/KubePi#98]
添加的集群证书过期后如何替换新证书呢？只有KubeOperator提供相关功能吗？

**Comment by frely** [comment]
不好意思，我没有描述清楚。之前用kubeconfig添加的集群，怎么替换新的kubeconfig呢。

**Comment by wanghe-fit2cloud** [comment]
了解。目前版本还做不到针对已导入集群更换 kubeconfig，后面版本支持吧。

当前版本，先通过 kubeconfig 导入新的集群吧。
