### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by alivv** [KubeOperator/KubePi#99]
**KubePi 版本**
v1.3.0

**Kubernetes 版本**
v1.18.8

**Bug 描述**
只给pods的get,list权限, 就能打pod终端; 进入pod终端的权限应该可控

**Bug 重现步骤(有截图更好)**
1. 工作负载->pods列表-> 终端

**Comment by wanghe-fit2cloud** [comment]
已优化，需要将 kubepi 升级到最新版本。

**Comment by alivv** [comment]
新版v1.5.3可以了，谢谢
